[[headers]]
for = "/*"
[headers.values]
ACCESS-CONTROL-ALLOW-ORIGIN = "*"
[build]
publish = "build"
command = "npm run build:netlify"
[context.production.environment]
NODE_ENV = "production"
VITE_APP_ERKENNINGEN_GRAPHQL_API_URL = "https://api.erkenningen.nl/graphql"
VITE_APP_ERKENNINGEN_ADMIN_URL = "https://erkenningen.nl"
VITE_APP_ERKENNINGEN_SITE_TYPE = "admin"
GASTBY_ERKENNINGEN_GRAPHQL_API_URL = "https://api.erkenningen.nl/graphql"
GASTBY_ERKENNINGEN_ADMIN_URL = "https://erkenningen.nl"
GASTBY_ERKENNINGEN_SITE_TYPE = "content"
[context.acceptance.environment]
NODE_ENV = "production"
VITE_APP_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.erkenningen.nl/graphql"
VITE_APP_ERKENNINGEN_ADMIN_URL = "https://acceptatie.erkenningen.nl"
VITE_APP_ERKENNINGEN_SITE_TYPE = "admin"
GASTBY_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.erkenningen.nl/graphql"
GASTBY_ERKENNINGEN_ADMIN_URL = "https://acceptatie.erkenningen.nl"
GASTBY_ERKENNINGEN_SITE_TYPE = "content"
[context.deploy-preview.environment]
NODE_ENV = "production"
VITE_APP_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.erkenningen.nl/graphql"
VITE_APP_ERKENNINGEN_ADMIN_URL = "https://acceptatie.erkenningen.nl"
VITE_APP_ERKENNINGEN_SITE_TYPE = "admin"
GASTBY_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.erkenningen.nl/graphql"
GASTBY_ERKENNINGEN_ADMIN_URL = "https://acceptatie.erkenningen.nl"
GASTBY_ERKENNINGEN_SITE_TYPE = "content"
